name: Deploy EC2 Instance

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Region'
        required: true
        default: 'us-east-1'
      vpc:
        description: 'VPC Name'
        required: true
        default: 'Application-Vpc'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Fetch Terraform modules
        run: terraform init

      - name: Run Terraform apply
        run: terraform apply -var "region=${{ github.event.inputs.region }}" -var "vpc_name=${{ github.event.inputs.vpc }}" -auto-approve
